EXP_DIR: ssh
TRAIN:
  IMS_PER_BATCH: 1
  BATCH_SIZE: 128
  SCALES: !!python/tuple [300,]
  MAX_SIZE: 400
  SNAPSHOT: 10000
  SNAPSHOT_INFIX: '3'
  ANCHOR_POSITIVE_OVERLAP: 0.4
  ANCHOR_NEGATIVE_OVERLAP: 0.2
  HARD_POSITIVE_MINING: True
  FORCE_FG_FOR_EACH_GT: False
TEST:
  ORIG_SIZE: False
  SCALES: !!python/tuple [300,]
  MAX_SIZE: 400

