
include(CMakeParseArguments)
function(assert cond)
    cmake_parse_arguments(OPT "" "MSG" "" ${ARGN})
    if (NOT ${cond})
        message(FATAL_ERROR "error: can't find ${cond}: ${ARG_MSG}")
    endif()
endfunction()

function(assert_var)
    foreach (v ${ARGN})
        if (NOT ${v})
            message(FATAL_ERROR "error: can't find ${v}")
        endif()
    endforeach()
endfunction()

function(assert_var2 prefix)
    foreach (v ${ARGN})
        if (NOT ${prefix}_${v})
            message(FATAL_ERROR "error: can't find ${v}")
        endif()
    endforeach()
endfunction()
