// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caffe2/proto/prof_dag.proto

#ifndef PROTOBUF_caffe2_2fproto_2fprof_5fdag_2eproto__INCLUDED
#define PROTOBUF_caffe2_2fproto_2fprof_5fdag_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace caffe2 {

// Internal implementation detail -- do not call these.
void CAFFE2_API protobuf_AddDesc_caffe2_2fproto_2fprof_5fdag_2eproto();
void protobuf_AssignDesc_caffe2_2fproto_2fprof_5fdag_2eproto();
void protobuf_ShutdownFile_caffe2_2fproto_2fprof_5fdag_2eproto();

class TwoNumberStatsProto;
class BlobProfile;
class ProfDAGProto;
class ProfDAGProtos;

// ===================================================================

class CAFFE2_API TwoNumberStatsProto : public ::google::protobuf::Message {
 public:
  TwoNumberStatsProto();
  virtual ~TwoNumberStatsProto();

  TwoNumberStatsProto(const TwoNumberStatsProto& from);

  inline TwoNumberStatsProto& operator=(const TwoNumberStatsProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TwoNumberStatsProto& default_instance();

  void Swap(TwoNumberStatsProto* other);

  // implements Message ----------------------------------------------

  TwoNumberStatsProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TwoNumberStatsProto& from);
  void MergeFrom(const TwoNumberStatsProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float mean = 1;
  inline bool has_mean() const;
  inline void clear_mean();
  static const int kMeanFieldNumber = 1;
  inline float mean() const;
  inline void set_mean(float value);

  // optional float stddev = 2;
  inline bool has_stddev() const;
  inline void clear_stddev();
  static const int kStddevFieldNumber = 2;
  inline float stddev() const;
  inline void set_stddev(float value);

  // optional int64 count = 3;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 3;
  inline ::google::protobuf::int64 count() const;
  inline void set_count(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:caffe2.TwoNumberStatsProto)
 private:
  inline void set_has_mean();
  inline void clear_has_mean();
  inline void set_has_stddev();
  inline void clear_has_stddev();
  inline void set_has_count();
  inline void clear_has_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  float mean_;
  float stddev_;
  ::google::protobuf::int64 count_;
  friend void CAFFE2_API protobuf_AddDesc_caffe2_2fproto_2fprof_5fdag_2eproto();
  friend void protobuf_AssignDesc_caffe2_2fproto_2fprof_5fdag_2eproto();
  friend void protobuf_ShutdownFile_caffe2_2fproto_2fprof_5fdag_2eproto();

  void InitAsDefaultInstance();
  static TwoNumberStatsProto* default_instance_;
};
// -------------------------------------------------------------------

class CAFFE2_API BlobProfile : public ::google::protobuf::Message {
 public:
  BlobProfile();
  virtual ~BlobProfile();

  BlobProfile(const BlobProfile& from);

  inline BlobProfile& operator=(const BlobProfile& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BlobProfile& default_instance();

  void Swap(BlobProfile* other);

  // implements Message ----------------------------------------------

  BlobProfile* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BlobProfile& from);
  void MergeFrom(const BlobProfile& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional .caffe2.TwoNumberStatsProto bytes_used = 3;
  inline bool has_bytes_used() const;
  inline void clear_bytes_used();
  static const int kBytesUsedFieldNumber = 3;
  inline const ::caffe2::TwoNumberStatsProto& bytes_used() const;
  inline ::caffe2::TwoNumberStatsProto* mutable_bytes_used();
  inline ::caffe2::TwoNumberStatsProto* release_bytes_used();
  inline void set_allocated_bytes_used(::caffe2::TwoNumberStatsProto* bytes_used);

  // @@protoc_insertion_point(class_scope:caffe2.BlobProfile)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_bytes_used();
  inline void clear_has_bytes_used();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::caffe2::TwoNumberStatsProto* bytes_used_;
  friend void CAFFE2_API protobuf_AddDesc_caffe2_2fproto_2fprof_5fdag_2eproto();
  friend void protobuf_AssignDesc_caffe2_2fproto_2fprof_5fdag_2eproto();
  friend void protobuf_ShutdownFile_caffe2_2fproto_2fprof_5fdag_2eproto();

  void InitAsDefaultInstance();
  static BlobProfile* default_instance_;
};
// -------------------------------------------------------------------

class CAFFE2_API ProfDAGProto : public ::google::protobuf::Message {
 public:
  ProfDAGProto();
  virtual ~ProfDAGProto();

  ProfDAGProto(const ProfDAGProto& from);

  inline ProfDAGProto& operator=(const ProfDAGProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProfDAGProto& default_instance();

  void Swap(ProfDAGProto* other);

  // implements Message ----------------------------------------------

  ProfDAGProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProfDAGProto& from);
  void MergeFrom(const ProfDAGProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required float mean = 2;
  inline bool has_mean() const;
  inline void clear_mean();
  static const int kMeanFieldNumber = 2;
  inline float mean() const;
  inline void set_mean(float value);

  // required float stddev = 3;
  inline bool has_stddev() const;
  inline void clear_stddev();
  static const int kStddevFieldNumber = 3;
  inline float stddev() const;
  inline void set_stddev(float value);

  // optional .caffe2.TwoNumberStatsProto execution_time = 4;
  inline bool has_execution_time() const;
  inline void clear_execution_time();
  static const int kExecutionTimeFieldNumber = 4;
  inline const ::caffe2::TwoNumberStatsProto& execution_time() const;
  inline ::caffe2::TwoNumberStatsProto* mutable_execution_time();
  inline ::caffe2::TwoNumberStatsProto* release_execution_time();
  inline void set_allocated_execution_time(::caffe2::TwoNumberStatsProto* execution_time);

  // repeated .caffe2.BlobProfile output_profile = 5;
  inline int output_profile_size() const;
  inline void clear_output_profile();
  static const int kOutputProfileFieldNumber = 5;
  inline const ::caffe2::BlobProfile& output_profile(int index) const;
  inline ::caffe2::BlobProfile* mutable_output_profile(int index);
  inline ::caffe2::BlobProfile* add_output_profile();
  inline const ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >&
      output_profile() const;
  inline ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >*
      mutable_output_profile();

  // @@protoc_insertion_point(class_scope:caffe2.ProfDAGProto)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_mean();
  inline void clear_has_mean();
  inline void set_has_stddev();
  inline void clear_has_stddev();
  inline void set_has_execution_time();
  inline void clear_has_execution_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  float mean_;
  float stddev_;
  ::caffe2::TwoNumberStatsProto* execution_time_;
  ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile > output_profile_;
  friend void CAFFE2_API protobuf_AddDesc_caffe2_2fproto_2fprof_5fdag_2eproto();
  friend void protobuf_AssignDesc_caffe2_2fproto_2fprof_5fdag_2eproto();
  friend void protobuf_ShutdownFile_caffe2_2fproto_2fprof_5fdag_2eproto();

  void InitAsDefaultInstance();
  static ProfDAGProto* default_instance_;
};
// -------------------------------------------------------------------

class CAFFE2_API ProfDAGProtos : public ::google::protobuf::Message {
 public:
  ProfDAGProtos();
  virtual ~ProfDAGProtos();

  ProfDAGProtos(const ProfDAGProtos& from);

  inline ProfDAGProtos& operator=(const ProfDAGProtos& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProfDAGProtos& default_instance();

  void Swap(ProfDAGProtos* other);

  // implements Message ----------------------------------------------

  ProfDAGProtos* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProfDAGProtos& from);
  void MergeFrom(const ProfDAGProtos& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .caffe2.ProfDAGProto stats = 1;
  inline int stats_size() const;
  inline void clear_stats();
  static const int kStatsFieldNumber = 1;
  inline const ::caffe2::ProfDAGProto& stats(int index) const;
  inline ::caffe2::ProfDAGProto* mutable_stats(int index);
  inline ::caffe2::ProfDAGProto* add_stats();
  inline const ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >&
      stats() const;
  inline ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >*
      mutable_stats();

  // optional string net_name = 2;
  inline bool has_net_name() const;
  inline void clear_net_name();
  static const int kNetNameFieldNumber = 2;
  inline const ::std::string& net_name() const;
  inline void set_net_name(const ::std::string& value);
  inline void set_net_name(const char* value);
  inline void set_net_name(const char* value, size_t size);
  inline ::std::string* mutable_net_name();
  inline ::std::string* release_net_name();
  inline void set_allocated_net_name(::std::string* net_name);

  // @@protoc_insertion_point(class_scope:caffe2.ProfDAGProtos)
 private:
  inline void set_has_net_name();
  inline void clear_has_net_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto > stats_;
  ::std::string* net_name_;
  friend void CAFFE2_API protobuf_AddDesc_caffe2_2fproto_2fprof_5fdag_2eproto();
  friend void protobuf_AssignDesc_caffe2_2fproto_2fprof_5fdag_2eproto();
  friend void protobuf_ShutdownFile_caffe2_2fproto_2fprof_5fdag_2eproto();

  void InitAsDefaultInstance();
  static ProfDAGProtos* default_instance_;
};
// ===================================================================


// ===================================================================

// TwoNumberStatsProto

// optional float mean = 1;
inline bool TwoNumberStatsProto::has_mean() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TwoNumberStatsProto::set_has_mean() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TwoNumberStatsProto::clear_has_mean() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TwoNumberStatsProto::clear_mean() {
  mean_ = 0;
  clear_has_mean();
}
inline float TwoNumberStatsProto::mean() const {
  // @@protoc_insertion_point(field_get:caffe2.TwoNumberStatsProto.mean)
  return mean_;
}
inline void TwoNumberStatsProto::set_mean(float value) {
  set_has_mean();
  mean_ = value;
  // @@protoc_insertion_point(field_set:caffe2.TwoNumberStatsProto.mean)
}

// optional float stddev = 2;
inline bool TwoNumberStatsProto::has_stddev() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TwoNumberStatsProto::set_has_stddev() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TwoNumberStatsProto::clear_has_stddev() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TwoNumberStatsProto::clear_stddev() {
  stddev_ = 0;
  clear_has_stddev();
}
inline float TwoNumberStatsProto::stddev() const {
  // @@protoc_insertion_point(field_get:caffe2.TwoNumberStatsProto.stddev)
  return stddev_;
}
inline void TwoNumberStatsProto::set_stddev(float value) {
  set_has_stddev();
  stddev_ = value;
  // @@protoc_insertion_point(field_set:caffe2.TwoNumberStatsProto.stddev)
}

// optional int64 count = 3;
inline bool TwoNumberStatsProto::has_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TwoNumberStatsProto::set_has_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TwoNumberStatsProto::clear_has_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TwoNumberStatsProto::clear_count() {
  count_ = GOOGLE_LONGLONG(0);
  clear_has_count();
}
inline ::google::protobuf::int64 TwoNumberStatsProto::count() const {
  // @@protoc_insertion_point(field_get:caffe2.TwoNumberStatsProto.count)
  return count_;
}
inline void TwoNumberStatsProto::set_count(::google::protobuf::int64 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:caffe2.TwoNumberStatsProto.count)
}

// -------------------------------------------------------------------

// BlobProfile

// optional string name = 1;
inline bool BlobProfile::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BlobProfile::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BlobProfile::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BlobProfile::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& BlobProfile::name() const {
  // @@protoc_insertion_point(field_get:caffe2.BlobProfile.name)
  return *name_;
}
inline void BlobProfile::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:caffe2.BlobProfile.name)
}
inline void BlobProfile::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:caffe2.BlobProfile.name)
}
inline void BlobProfile::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:caffe2.BlobProfile.name)
}
inline ::std::string* BlobProfile::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:caffe2.BlobProfile.name)
  return name_;
}
inline ::std::string* BlobProfile::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void BlobProfile::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:caffe2.BlobProfile.name)
}

// optional .caffe2.TwoNumberStatsProto bytes_used = 3;
inline bool BlobProfile::has_bytes_used() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BlobProfile::set_has_bytes_used() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BlobProfile::clear_has_bytes_used() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BlobProfile::clear_bytes_used() {
  if (bytes_used_ != NULL) bytes_used_->::caffe2::TwoNumberStatsProto::Clear();
  clear_has_bytes_used();
}
inline const ::caffe2::TwoNumberStatsProto& BlobProfile::bytes_used() const {
  // @@protoc_insertion_point(field_get:caffe2.BlobProfile.bytes_used)
  return bytes_used_ != NULL ? *bytes_used_ : *default_instance_->bytes_used_;
}
inline ::caffe2::TwoNumberStatsProto* BlobProfile::mutable_bytes_used() {
  set_has_bytes_used();
  if (bytes_used_ == NULL) bytes_used_ = new ::caffe2::TwoNumberStatsProto;
  // @@protoc_insertion_point(field_mutable:caffe2.BlobProfile.bytes_used)
  return bytes_used_;
}
inline ::caffe2::TwoNumberStatsProto* BlobProfile::release_bytes_used() {
  clear_has_bytes_used();
  ::caffe2::TwoNumberStatsProto* temp = bytes_used_;
  bytes_used_ = NULL;
  return temp;
}
inline void BlobProfile::set_allocated_bytes_used(::caffe2::TwoNumberStatsProto* bytes_used) {
  delete bytes_used_;
  bytes_used_ = bytes_used;
  if (bytes_used) {
    set_has_bytes_used();
  } else {
    clear_has_bytes_used();
  }
  // @@protoc_insertion_point(field_set_allocated:caffe2.BlobProfile.bytes_used)
}

// -------------------------------------------------------------------

// ProfDAGProto

// required string name = 1;
inline bool ProfDAGProto::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProfDAGProto::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProfDAGProto::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProfDAGProto::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& ProfDAGProto::name() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.name)
  return *name_;
}
inline void ProfDAGProto::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.name)
}
inline void ProfDAGProto::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:caffe2.ProfDAGProto.name)
}
inline void ProfDAGProto::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:caffe2.ProfDAGProto.name)
}
inline ::std::string* ProfDAGProto::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProto.name)
  return name_;
}
inline ::std::string* ProfDAGProto::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ProfDAGProto::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:caffe2.ProfDAGProto.name)
}

// required float mean = 2;
inline bool ProfDAGProto::has_mean() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProfDAGProto::set_has_mean() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProfDAGProto::clear_has_mean() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProfDAGProto::clear_mean() {
  mean_ = 0;
  clear_has_mean();
}
inline float ProfDAGProto::mean() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.mean)
  return mean_;
}
inline void ProfDAGProto::set_mean(float value) {
  set_has_mean();
  mean_ = value;
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.mean)
}

// required float stddev = 3;
inline bool ProfDAGProto::has_stddev() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProfDAGProto::set_has_stddev() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProfDAGProto::clear_has_stddev() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProfDAGProto::clear_stddev() {
  stddev_ = 0;
  clear_has_stddev();
}
inline float ProfDAGProto::stddev() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.stddev)
  return stddev_;
}
inline void ProfDAGProto::set_stddev(float value) {
  set_has_stddev();
  stddev_ = value;
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.stddev)
}

// optional .caffe2.TwoNumberStatsProto execution_time = 4;
inline bool ProfDAGProto::has_execution_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProfDAGProto::set_has_execution_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProfDAGProto::clear_has_execution_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProfDAGProto::clear_execution_time() {
  if (execution_time_ != NULL) execution_time_->::caffe2::TwoNumberStatsProto::Clear();
  clear_has_execution_time();
}
inline const ::caffe2::TwoNumberStatsProto& ProfDAGProto::execution_time() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.execution_time)
  return execution_time_ != NULL ? *execution_time_ : *default_instance_->execution_time_;
}
inline ::caffe2::TwoNumberStatsProto* ProfDAGProto::mutable_execution_time() {
  set_has_execution_time();
  if (execution_time_ == NULL) execution_time_ = new ::caffe2::TwoNumberStatsProto;
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProto.execution_time)
  return execution_time_;
}
inline ::caffe2::TwoNumberStatsProto* ProfDAGProto::release_execution_time() {
  clear_has_execution_time();
  ::caffe2::TwoNumberStatsProto* temp = execution_time_;
  execution_time_ = NULL;
  return temp;
}
inline void ProfDAGProto::set_allocated_execution_time(::caffe2::TwoNumberStatsProto* execution_time) {
  delete execution_time_;
  execution_time_ = execution_time;
  if (execution_time) {
    set_has_execution_time();
  } else {
    clear_has_execution_time();
  }
  // @@protoc_insertion_point(field_set_allocated:caffe2.ProfDAGProto.execution_time)
}

// repeated .caffe2.BlobProfile output_profile = 5;
inline int ProfDAGProto::output_profile_size() const {
  return output_profile_.size();
}
inline void ProfDAGProto::clear_output_profile() {
  output_profile_.Clear();
}
inline const ::caffe2::BlobProfile& ProfDAGProto::output_profile(int index) const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.output_profile)
  return output_profile_.Get(index);
}
inline ::caffe2::BlobProfile* ProfDAGProto::mutable_output_profile(int index) {
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProto.output_profile)
  return output_profile_.Mutable(index);
}
inline ::caffe2::BlobProfile* ProfDAGProto::add_output_profile() {
  // @@protoc_insertion_point(field_add:caffe2.ProfDAGProto.output_profile)
  return output_profile_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >&
ProfDAGProto::output_profile() const {
  // @@protoc_insertion_point(field_list:caffe2.ProfDAGProto.output_profile)
  return output_profile_;
}
inline ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >*
ProfDAGProto::mutable_output_profile() {
  // @@protoc_insertion_point(field_mutable_list:caffe2.ProfDAGProto.output_profile)
  return &output_profile_;
}

// -------------------------------------------------------------------

// ProfDAGProtos

// repeated .caffe2.ProfDAGProto stats = 1;
inline int ProfDAGProtos::stats_size() const {
  return stats_.size();
}
inline void ProfDAGProtos::clear_stats() {
  stats_.Clear();
}
inline const ::caffe2::ProfDAGProto& ProfDAGProtos::stats(int index) const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProtos.stats)
  return stats_.Get(index);
}
inline ::caffe2::ProfDAGProto* ProfDAGProtos::mutable_stats(int index) {
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProtos.stats)
  return stats_.Mutable(index);
}
inline ::caffe2::ProfDAGProto* ProfDAGProtos::add_stats() {
  // @@protoc_insertion_point(field_add:caffe2.ProfDAGProtos.stats)
  return stats_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >&
ProfDAGProtos::stats() const {
  // @@protoc_insertion_point(field_list:caffe2.ProfDAGProtos.stats)
  return stats_;
}
inline ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >*
ProfDAGProtos::mutable_stats() {
  // @@protoc_insertion_point(field_mutable_list:caffe2.ProfDAGProtos.stats)
  return &stats_;
}

// optional string net_name = 2;
inline bool ProfDAGProtos::has_net_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProfDAGProtos::set_has_net_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProfDAGProtos::clear_has_net_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProfDAGProtos::clear_net_name() {
  if (net_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    net_name_->clear();
  }
  clear_has_net_name();
}
inline const ::std::string& ProfDAGProtos::net_name() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProtos.net_name)
  return *net_name_;
}
inline void ProfDAGProtos::set_net_name(const ::std::string& value) {
  set_has_net_name();
  if (net_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    net_name_ = new ::std::string;
  }
  net_name_->assign(value);
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProtos.net_name)
}
inline void ProfDAGProtos::set_net_name(const char* value) {
  set_has_net_name();
  if (net_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    net_name_ = new ::std::string;
  }
  net_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:caffe2.ProfDAGProtos.net_name)
}
inline void ProfDAGProtos::set_net_name(const char* value, size_t size) {
  set_has_net_name();
  if (net_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    net_name_ = new ::std::string;
  }
  net_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:caffe2.ProfDAGProtos.net_name)
}
inline ::std::string* ProfDAGProtos::mutable_net_name() {
  set_has_net_name();
  if (net_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    net_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProtos.net_name)
  return net_name_;
}
inline ::std::string* ProfDAGProtos::release_net_name() {
  clear_has_net_name();
  if (net_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = net_name_;
    net_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ProfDAGProtos::set_allocated_net_name(::std::string* net_name) {
  if (net_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete net_name_;
  }
  if (net_name) {
    set_has_net_name();
    net_name_ = net_name;
  } else {
    clear_has_net_name();
    net_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:caffe2.ProfDAGProtos.net_name)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace caffe2

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_caffe2_2fproto_2fprof_5fdag_2eproto__INCLUDED
